// backend/routes/chat.js
// ============================================================
// CHAT ROUTES — Handles support chat message history and sessions.
// Real-time messaging itself happens via Socket.IO (see server.js).
// These routes are for fetching/managing chat history via REST API.
//
// Session rules:
//   - Sessions expire after 1 hour of inactivity
//   - Staff can manually end sessions (sends a farewell message)
//   - After session end, 5 minutes of cooldown before clearing chat
// ============================================================
const express = require('express');
const router = express.Router();
const ChatMessage = require('../models/ChatMessage');
const { authMiddleware, checkSupportOrAdmin } = require('../middleware/auth');
const User = require('../models/User');

// ----------------------------------------------------------
// GET CHAT HISTORY (for regular users)
// GET /api/chat/history
// Returns the current chat session's messages.
// If the last message is older than 1 hour, returns empty (new session).
// If the session was ended by staff, waits 5 min then clears.
// ----------------------------------------------------------
router.get('/history', authMiddleware, async (req, res) => {
  try {
    // Get all messages for the current user, oldest first
    const messages = await ChatMessage.find({ userId: req.user.id })
      .sort({ createdAt: 1 });
    
    // No messages at all → empty chat
    if (messages.length === 0) {
      return res.json({ success: true, count: 0, data: [] });
    }

    const now = new Date();
    const latestMsg = messages[messages.length - 1];
    const latestMsgTime = new Date(latestMsg.createdAt);
    
    // --- SESSION END CHECK ---
    // If the last message is a "session end" marker (staff clicked "End Session"):
    // Wait 5 minutes to show the farewell message, then clear for a fresh session
    if (latestMsg.isSessionEnd) {
      const diffMs = now - latestMsgTime;
      const diffMinutes = diffMs / (1000 * 60);
      if (diffMinutes >= 5) {
        return res.json({ 
          success: true, 
          count: 0, 
          data: [],
          info: "Session ended by staff" 
        });
      }
      // If within 5 minutes, show the current session (including farewell)
    } else {
      // --- STALE SESSION CHECK ---
      // If no activity for 1+ hour, treat as a new session (clear old messages)
      const diffMs = now - latestMsgTime;
      const diffHours = diffMs / (1000 * 60 * 60);

      if (diffHours >= 1) {
        return res.json({ 
          success: true, 
          count: 0, 
          data: [],
          info: "Session expired" 
        });
      }
    }

    // --- FIND CURRENT SESSION ---
    // Walk backwards through messages. Stop when there's a gap > 1 hour
    // or when we hit a session-end marker (from a previous session).
    let sessionStartIndex = 0;
    const ONE_HOUR_MS = 60 * 60 * 1000;

    for (let i = messages.length - 1; i > 0; i--) {
      const current = new Date(messages[i].createdAt);
      const previous = new Date(messages[i-1].createdAt);
      
      if ((current - previous > ONE_HOUR_MS) || (messages[i-1].isSessionEnd)) {
        sessionStartIndex = i;  // Current session starts here
        break;
      }
    }

    // Return only the current session's messages
    const sessionMessages = messages.slice(sessionStartIndex);

    res.json({
      success: true,
      count: sessionMessages.length,
      data: sessionMessages
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

// ----------------------------------------------------------
// END CHAT SESSION (staff only)
// POST /api/chat/admin/end-session/:userId
// Sends an automated farewell message and marks the session as ended.
// The user sees "This session is now closed" in their chat.
// ----------------------------------------------------------
router.post('/admin/end-session/:userId', authMiddleware, checkSupportOrAdmin, async (req, res) => {
  try {
    const userId = req.params.userId;
    const adminId = req.user.id;
    const adminName = req.user.name || "iPark Support";

    // Create an automated farewell message
    const goodbyeMessage = new ChatMessage({
      userId,
      senderId: adminId,
      senderName: adminName,
      message: "Thank you for contacting iPark Support. We hope we were able to assist you effectively. This session is now closed. Have a great day!",
      isAdmin: true,
      isAutoGenerated: true,
      isSessionEnd: true    // This flag tells the app this session is over
    });

    await goodbyeMessage.save();
    
    // Send the farewell message to the user in real-time
    const io = req.app.get('io');
    if (io) {
      io.to(userId.toString()).emit('receive_chat_message', goodbyeMessage.toJSON());
    }

    res.json({
      success: true,
      message: "Chat session ended successfully",
      data: goodbyeMessage
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

// ----------------------------------------------------------
// GET ALL CONVERSATIONS (staff only)
// GET /api/chat/admin/conversations
// Returns a list of all unique user conversations, showing:
//   - User name and details
//   - The last message in each conversation
//   - Sorted by most recent activity
// Used in the admin Chat List screen.
// ----------------------------------------------------------
router.get('/admin/conversations', authMiddleware, checkSupportOrAdmin, async (req, res) => {
  try {
    // MongoDB aggregation pipeline:
    // 1. Exclude auto-generated messages (greetings)
    // 2. Group by userId → get the latest message per user
    // 3. Join with Users collection to get user names
    // 4. Sort by most recent conversation first
    const conversations = await ChatMessage.aggregate([
      { $match: { isAutoGenerated: { $ne: true } } }, 
      { $sort: { createdAt: -1 } },
      {
        $group: {
          _id: '$userId',
          lastMessage: { $first: '$message' },
          lastSenderName: { $first: '$senderName' },
          lastCreatedAt: { $first: '$createdAt' }
        }
      },
      {
        $lookup: {
          from: 'users',
          localField: '_id',
          foreignField: '_id',
          as: 'userDetails'
        }
      },
      { $unwind: '$userDetails' },
      { $sort: { lastCreatedAt: -1 } }
    ]);

    res.json({
      success: true,
      count: conversations.length,
      data: conversations
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

// ----------------------------------------------------------
// GET CHAT HISTORY FOR A SPECIFIC USER (staff only)
// GET /api/chat/admin/history/:userId
// Returns up to 100 messages for a specific user.
// Used when staff clicks on a user in the chat list.
// ----------------------------------------------------------
router.get('/admin/history/:userId', authMiddleware, checkSupportOrAdmin, async (req, res) => {
  try {
    const messages = await ChatMessage.find({ 
        userId: req.params.userId
      })
      .sort({ createdAt: 1 })
      .limit(100);             // Cap at 100 messages to prevent large responses
    
    res.json({
      success: true,
      count: messages.length,
      data: messages
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
});

module.exports = router;
