// ChatMessage.js
const mongoose = require('mongoose');

const ChatMessageSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  senderId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  senderName: { type: String, required: true },
  message: { type: String, required: true, trim: true },
  isAdmin: { type: Boolean, default: false },
  isAutoGenerated: { type: Boolean, default: false },
  isSessionEnd: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
  clientMsgId: { type: String, required: false }
});

module.exports = mongoose.model('ChatMessage', ChatMessageSchema);


// ErrorLog.js
const ErrorLogSchema = new mongoose.Schema({
  errorCode: { type: String, required: true },
  message: { type: String, required: true },
  stack: { type: String },
  path: { type: String },
  method: { type: String },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  metadata: { type: Object },
  isResolved: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

ErrorLogSchema.index({ errorCode: 1 });
ErrorLogSchema.index({ createdAt: -1 });

module.exports = mongoose.model('ErrorLog', ErrorLogSchema);


// Mall.js
const MallSchema = new mongoose.Schema({
  name: { type: String, required: true },
  location: { type: String, required: true },
  description: { type: String, default: '' },
  address: { type: String },
  photoUrl: { type: String },
  totalSpots: { type: Number, default: 0 },
  pricePerHour: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Mall', MallSchema);


// PointHistory.js
const PointHistorySchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  mallId: { type: mongoose.Schema.Types.ObjectId, ref: 'Mall', index: true },
  amount: { type: Number, required: true },
  reason: { type: String, required: true },
  createdAt: { type: Date, default: Date.now, index: true }
});

module.exports = mongoose.model('PointHistory', PointHistorySchema);


// PromoCode.js
const PromoCodeSchema = new mongoose.Schema({
  code: { type: String, required: true, unique: true },
  discount: { type: Number, required: true },
  targetUsers: { type: Number, default: 0 },
  usageCount: { type: Number, default: 0 },
  usedBy: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('PromoCode', PromoCodeSchema);


// Reservation.js
const ReservationSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  spotId: { type: mongoose.Schema.Types.ObjectId, ref: 'Spot', required: true },
  mallId: { type: mongoose.Schema.Types.ObjectId, ref: 'Mall', required: true },
  carPlate: { type: String, required: true },
  startTime: { type: Date, required: true },
  endTime: { type: Date, required: true },
  status: { type: String, enum: ['pending', 'active', 'completed', 'cancelled', 'overtime'], default: 'pending' },
  amount: { type: Number, default: 0, set: (v) => typeof v === 'string' ? parseFloat(v) || 0 : v },
  pointsEarned: { type: Number, default: 0 },
  promoCodeUsed: { type: String },
  actualStartTime: { type: Date },
  durationMinutes: { type: Number },
  notified15: { type: Boolean, default: false },
  notified30: { type: Boolean, default: false },
  notifiedEnd30: { type: Boolean, default: false },
  notifiedEnd15: { type: Boolean, default: false },
  notifiedEnd5: { type: Boolean, default: false },
  notifiedEnd0: { type: Boolean, default: false },
  carEntered: { type: Boolean, default: false },
  gateOpened: { type: Boolean, default: false },
  needsReverify: { type: Boolean, default: false },
  overtimeAlertSent: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

ReservationSchema.index({ userId: 1 });
ReservationSchema.index({ createdAt: -1 });
ReservationSchema.index({ userId: 1, createdAt: -1 });
ReservationSchema.index({ status: 1, endTime: 1 });

module.exports = mongoose.model('Reservation', ReservationSchema);


// Spot.js
const SpotSchema = new mongoose.Schema({
  mallId: { type: mongoose.Schema.Types.ObjectId, ref: 'Mall', required: true },
  spotNumber: { type: String, required: true },
  status: { type: String, enum: ['green', 'yellow', 'red', 'disabled'], default: 'green' },
  reservedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  reservationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Reservation' },
  lastUpdated: { type: Date, default: Date.now }
});

SpotSchema.index({ mallId: 1 });
SpotSchema.index({ status: 1 });

module.exports = mongoose.model('Spot', SpotSchema);


// SupportTicket.js
const SupportTicketSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  subject: { type: String, required: true, trim: true },
  message: { type: String, required: true, trim: true },
  status: { type: String, enum: ['open', 'solved'], default: 'open' },
  adminResponse: { type: String, trim: true },
  respondedAt: { type: Date },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('SupportTicket', SupportTicketSchema);


// User.js
const UserSchema = new mongoose.Schema({
  phoneNumber: { type: String, required: true, unique: true, trim: true },
  name: { type: String, required: true, trim: true },
  email: { type: String, required: true, unique: true, trim: true, lowercase: true },
  nationalId: { type: String, required: true, unique: true, trim: true },
  carPlate: { type: String, default: '', trim: true },
  role: { type: String, default: 'user', enum: ['user', 'admin', 'support'] },
  points: { type: Number, default: 0 },
  photoUrl: { type: String, default: '' },
  pendingReward: { type: String, default: null },
  isVerified: { type: Boolean, default: false },
  isBanned: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('User', UserSchema);
