// backend/server.js
/**
 * iPark Backend Server
 * 
 * This is the main entry point for the iPark Node.js/Express server.
 * It handles:
 * - Express server configuration and middleware
 * - MongoDB connection
 * - RESTful API routes
 * - Real-time communication via Socket.IO
 * - Background maintenance tasks (Spot status synchronization)
 */

require('dotenv').config();
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const connectDB = require('./config/db');
const authRoutes = require('./routes/auth');
const mallRoutes = require('./routes/mall');
const reservationRoutes = require('./routes/reservation');
const adminRoutes = require('./routes/admin');
const userRoutes = require('./routes/user'); 
const chatRoutes = require('./routes/chat');
const errorHandler = require('./middleware/errorHandler');
const ErrorLog = require('./models/ErrorLog');
const catchAsync = require('./utils/catchAsync');
const AppError = require('./utils/appError');
const path = require('path');

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

const iotManager = require('./utils/iotManager');
iotManager.init(io);

// Attach Socket.IO and IoT manager instances to the app for use in route handlers
app.set('io', io);
app.set('iotManager', iotManager);
app.set('trust proxy', 1);

// Route WebSocket upgrades on /ws/iot to the iotManager
server.on('upgrade', (request, socket, head) => {
  const pathname = request.url.split('?')[0];
  if (pathname === '/ws/iot') {
    iotManager.handleUpgrade(request, socket, head);
  }
});

// --- Middleware Stack ---

app.use(helmet()); // Basic security headers
app.use(cors());   // Enable Cross-Origin Resource Sharing
app.use(express.json()); // Parse JSON bodies
app.use(express.urlencoded({ extended: true }));

// Serve static files (like profile pictures) from the 'uploads' directory
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// Rate Limiting: Prevents brute-force attacks by limiting requests per IP
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // Limit each IP to 100 requests per window
  message: {
    success: false,
    message: 'Too many requests from this IP, please try again after 15 minutes'
  },
  standardHeaders: true,
  legacyHeaders: false,
});
app.use('/api/', limiter);

// Initialize Database Connection
connectDB();

// --- REST API Routes ---

app.use('/api/auth', authRoutes);         // Login, Register, Profile
app.use('/api/mall', mallRoutes);         // Mall listing and info
app.use('/api/reservation', reservationRoutes); // Booking and status updates
app.use('/api/admin', adminRoutes);       // Dashboard and system management
app.use('/api/user', userRoutes);         // User settings and lists
app.use('/api/chat', chatRoutes);         // Support chat history

// --- Real-time Socket.IO Logic ---

io.on('connection', (socket) => {
  console.log('User connected:', socket.id);

  /**
   * Support Chat: Join a dedicated room for the user.
   * Sends an automated greeting if the user is starting a new session.
   */
  socket.on('join_chat', async (data) => {
    const { userId, userName } = data;
    if (!userId) return;
    const room = userId.toString();
    socket.join(room);
    console.log(`User ${userName} (${room}) joined support chat.`);

    const ChatMessage = require('./models/ChatMessage');
    const lastMsg = await ChatMessage.findOne({ userId }).sort({ createdAt: -1 });
    
    // Auto-greeting logic: Only send if no previous messages OR last message is > 1 hour old
    const oneHourAgo = new Date(Date.now() - 3600000);
    const shouldSendGreeting = !lastMsg || new Date(lastMsg.createdAt) < oneHourAgo;

    if (shouldSendGreeting) {
      const automatedMsg = {
        userId: userId,
        senderId: '000000000000000000000001', // Virtual Support System ID
        senderName: 'Sarah from iPark Support',
        message: `Hi ${userName}, welcome back to iPark support! How can we help you today?`,
        isAdmin: true,
        isAutoGenerated: true,
        createdAt: new Date()
      };
      
      const savedMsg = await ChatMessage.create(automatedMsg);
      io.to(userId).emit('receive_chat_message', savedMsg.toJSON());
    }
  });

  /**
   * Identifies the socket with a User ID.
   * Allows the server to target specific users for notifications.
   */
  socket.on('identify_user', (data) => {
    const { userId } = data;
    if (userId) {
      socket.join(userId.toString());
      console.log(`Socket ${socket.id} identified as user ${userId}`);
    }
  });

  /**
   * Forwards a chat message to the appropriate room.
   */
  socket.on('send_chat_message', async (data) => {
    try {
      const ChatMessage = require('./models/ChatMessage');
      const newMessage = await ChatMessage.create(data);
      const plainMsg = newMessage.toJSON();
      
      const room = data.userId.toString();
      io.to(room).emit('receive_chat_message', plainMsg);

      // --- ADMIN / SUPPORT NOTIFICATION ---
      // If the message is from a regular user (not an admin), alert the staff
      if (!data.isAdmin && !data.isAutoGenerated) {
        const User = require('./models/User');
        const staffUsers = await User.find({ role: { $in: ['admin', 'support'] } });
        staffUsers.forEach(staff => {
          io.to(staff._id.toString()).emit('admin_support_alert', {
            type: 'chat',
            title: 'New Chat Message',
            body: `${data.senderName || 'A user'} sent a message: ${data.message}`,
            data: plainMsg
          });
        });
      }
    } catch (err) {
      console.error('Socket error in send_chat_message:', err);
    }
  });

  socket.on('disconnect', () => {
    console.log('User disconnected:', socket.id);
  });
});

// --- System Routes ---

// Health Check: Used by monitoring tools to ensure server is responsive
app.get('/health', (req, res) => {
  res.status(200).json({ 
    status: 'OK', 
    uptime: process.uptime(),
    serverTime: new Date().toISOString(),
    timezoneOffset: new Date().getTimezoneOffset()
  });
});

/**
 * Frontend Error Reporting: Allows the Flutter app to log crashes/errors to the server.
 * Triggers a real-time alert for admins.
 */
app.post('/api/admin/report-client-error', catchAsync(async (req, res) => {
  const { errorCode, message, stack, metadata } = req.body;
  const log = await ErrorLog.create({
    errorCode: errorCode || 'FE-GEN-001',
    message: message || 'Unknown frontend error',
    stack,
    path: 'Frontend/App',
    userId: req.user ? req.user.id : null,
    metadata
  });
  
  const io = req.app.get('io');
  if (io) {
    io.emit('system_error_alert', {
      logId: log._id,
      errorCode: errorCode || 'FE-GEN-001',
      message: message || 'Frontend Crash Detected',
      path: 'Frontend',
      timestamp: new Date()
    });
  }

  res.json({ success: true });
}));

app.get('/', (req, res) => {
  res.send('<h1>iPark Server is Live!</h1><p>Public Connection Active via LocalTunnel.</p>');
});

// 404 Handler for undefined routes
app.use((req, res, next) => {
  next(new AppError('No route found on this server', 404, 'BE-NET-404'));
});

// Global Centralized Error Handler
app.use(errorHandler);

// --- Background Maintenance Job ---

const Reservation = require('./models/Reservation');
const Spot = require('./models/Spot');

/**
 * Auto-Sync Status Job: Runs every 5 seconds.
 * 
 * This is the "brain" of the parking system. It:
 * 1. Checks all active reservations.
 * 2. Changes spot status to RED when a user's booking start time approaches.
 * 3. Changes spot status to YELLOW when a booking is about to end.
 * 4. Sends push-style notifications (via Socket.IO) for unverified arrivals.
 * 5. Automatically completes or cancels expired reservations.
 * 6. OVERTIME: If a reservation expires but the car is still in the spot,
 *    keeps monitoring the IR sensor, alerts admins/support, and does NOT
 *    auto-complete the reservation until the car actually leaves.
 */
const startStatusSyncJob = (io) => {
  setInterval(async () => {
    try {
      const now = new Date();
      
      // Fetch both active/pending AND overtime reservations
      const activeReservations = await Reservation.find({
        status: { $in: ['pending', 'active', 'overtime'] }
      }).lean();

      const targetStatuses = new Map(); // Map: spotId -> { status, mallId, resId, startTime }

      for (const res of activeReservations) {
        if (!res.startTime || !res.endTime) continue;
        
        const start = new Date(res.startTime);
        const end = new Date(res.endTime);
        
        // Configuration: 15 minutes before/after thresholds
        const arrivalThreshold = new Date(start.getTime() - 15 * 60 * 1000);
        const exitThreshold = new Date(end.getTime() - 15 * 60 * 1000);

        // --- EXPIRY LOGIC ---
        if (now >= end) {
          // Send 0m expiration notification once
          if (!res.notifiedEnd0) {
            io.to(res.userId.toString()).emit('ending_notification', {
              reservationId: res._id,
              minutes: 0,
              isExpired: true,
              isOvertime: res.carEntered === true
            });
            await Reservation.findByIdAndUpdate(res._id, { notifiedEnd0: true });
            res.notifiedEnd0 = true; // Update local ref
          }

          // ============================================================
          // OVERTIME DETECTION
          // If the car is still physically in the spot (carEntered=true),
          // we do NOT complete/cancel the reservation yet. Instead we:
          //   1. Mark it as 'overtime' so the sensor stays active.
          //   2. Send a one-time alert to all admins via Socket.IO.
          //   3. Log it in the ErrorLog for the admin dashboard.
          // The reservation will complete naturally once the IoT sensor
          // reports that the car has left (carEntered becomes false via
          // a status_change event in iotManager.js).
          // ============================================================
          if (res.carEntered === true) {
            // Only process overtime if we haven't already flagged it
            if (res.status !== 'overtime') {
              console.log(`[OVERTIME] ⚠️  Reservation ${res._id} has EXPIRED but car is still in spot ${res.spotId}! Marking as overtime.`);
              
              // Mark reservation as overtime so the sync loop keeps tracking it
              await Reservation.findByIdAndUpdate(res._id, { status: 'overtime' });

              // Fetch spot name for a meaningful alert message
              const spot = await Spot.findById(res.spotId).populate('mallId', 'name');
              const spotLabel = spot
                ? `${spot.mallId ? spot.mallId.name : 'Mall'} - Spot ${spot.spotNumber || res.spotId}`
                : `Spot ${res.spotId}`;

              const alertMsg = `🚨 OVERTIME ALERT: A car in ${spotLabel} has exceeded its reservation time (ended ${end.toLocaleTimeString()}). Car plate: ${res.carPlate}. Reservation ID: ${res._id}.`;

              console.log(`[OVERTIME] ${alertMsg}`);

              // Send real-time alert to all connected admin dashboards
              io.emit('overtime_alert', {
                reservationId: res._id.toString(),
                spotId: res.spotId.toString(),
                spotLabel,
                carPlate: res.carPlate,
                endTime: end.toISOString(),
                userId: res.userId.toString(),
                message: alertMsg,
                timestamp: now.toISOString()
              });

              // Log it as a system error/alert in the ErrorLog collection
              try {
                await ErrorLog.create({
                  errorCode: 'IOT-OVERTIME-001',
                  message: alertMsg,
                  path: 'Server/StatusSyncJob',
                  metadata: {
                    reservationId: res._id.toString(),
                    spotId: res.spotId.toString(),
                    spotLabel,
                    carPlate: res.carPlate,
                    scheduledEnd: end.toISOString()
                  }
                });
              } catch (logErr) {
                console.error('[OVERTIME] Failed to log to ErrorLog:', logErr.message);
              }
            }

            // Keep the spot marked RED (car is physically still there)
            targetStatuses.set(res.spotId.toString(), {
              status: 'red',
              mallId: res.mallId,
              resId: res._id,
              startTime: res.startTime
            });

            continue; // Skip the normal completion logic below
          }

          // No car in spot → normal expiry flow
          if (res.status === 'active' || res.status === 'overtime') {
            await Reservation.findByIdAndUpdate(res._id, { status: 'completed' });
          } else {
            // If user never showed up (verified arrival), cancel it
            await Reservation.findByIdAndUpdate(res._id, { status: 'cancelled' });
          }
          continue;
        }

        // --- COLOR LOGIC ---
        let currentTargetStatus = 'green';
        if (now >= exitThreshold) {
          currentTargetStatus = 'yellow'; // Leaving soon
        } else if (now >= arrivalThreshold) {
          currentTargetStatus = 'red';    // Booked/Occupied
        }

        if (currentTargetStatus !== 'green') {
          const existing = targetStatuses.get(res.spotId.toString());
          // Red priority over Yellow for overlapping reservations
          if (!existing || currentTargetStatus === 'red') {
            targetStatuses.set(res.spotId.toString(), { 
              status: currentTargetStatus, 
              mallId: res.mallId, 
              resId: res._id,
              startTime: res.startTime
            });
          }
        }

        // --- ARRIVAL NOTIFICATION LOGIC ---
        // Pings the user if they haven't verified their arrival at the spot yet.
        if (res.status === 'pending') {
          const diffMs = now - start;
          const diffMin = diffMs / (1000 * 60);

          if (diffMin >= 30 && !res.notified30) {
            io.to(res.userId.toString()).emit('arrival_notification', {
              reservationId: res._id,
              type: 'warning',
              minutes: 30
            });
            await Reservation.findByIdAndUpdate(res._id, { notified30: true });
          } else if (diffMin >= 15 && !res.notified15) {
            io.to(res.userId.toString()).emit('arrival_notification', {
              reservationId: res._id,
              type: 'reminder',
              minutes: 15
            });
            await Reservation.findByIdAndUpdate(res._id, { notified15: true });
          }
        }

        // --- ENDING NOTIFICATION LOGIC ---
        // Pings the user when their active reservation is ending soon
        if (res.status === 'active') {
          const leftMs = end - now;
          const leftMin = leftMs / (1000 * 60);

          if (leftMin <= 5 && !res.notifiedEnd5) {
            io.to(res.userId.toString()).emit('ending_notification', {
              reservationId: res._id,
              minutes: 5,
              isExpired: false
            });
            await Reservation.findByIdAndUpdate(res._id, { notifiedEnd5: true, notifiedEnd15: true, notifiedEnd30: true });
          } else if (leftMin <= 15 && !res.notifiedEnd15) {
            io.to(res.userId.toString()).emit('ending_notification', {
              reservationId: res._id,
              minutes: 15,
              isExpired: false
            });
            await Reservation.findByIdAndUpdate(res._id, { notifiedEnd15: true, notifiedEnd30: true });
          } else if (leftMin <= 30 && !res.notifiedEnd30) {
            io.to(res.userId.toString()).emit('ending_notification', {
              reservationId: res._id,
              minutes: 30,
              isExpired: false
            });
            await Reservation.findByIdAndUpdate(res._id, { notifiedEnd30: true });
          }
        }
      }

      // --- APPLY DB CHANGES AND BROADCAST ---
      const allSpots = await Spot.find().lean();

      for (const spot of allSpots) {
        const spotIdStr = spot._id.toString();
        if (spot.status === 'disabled') continue; // Manual override

        const target = targetStatuses.get(spotIdStr);
        const desiredStatus = target ? target.status : 'green';
        const desiredResId = target ? target.resId : null;

        if (spot.status !== desiredStatus) {
          try {
            await Spot.findByIdAndUpdate(spot._id, { 
              status: desiredStatus, 
              reservationId: desiredResId 
            });
            
            // Notify all clients to update UI colors immediately
            io.emit('spot_status_changed', { 
              spotId: spotIdStr, 
              mallId: spot.mallId, 
              status: desiredStatus 
            });
            
            console.log(`[STATUS SYNC] ${spot.spotNumber}: ${spot.status} -> ${desiredStatus}`);
          } catch (spotErr) {
            console.error(`[SPOT SYNC FAILED] Spot ${spotIdStr}:`, spotErr.message);
          }
        }
      }

    } catch (error) {
      console.error('[GLOBAL STATUS SYNC ERROR]:', error.message);
    }
  }, 5000); 
};

// --- Server Startup ---

const PORT = process.env.PORT || 5000;
const HOST = '0.0.0.0'; // Listen on all network interfaces (allows LAN access from ESP32)
server.listen(PORT, HOST, () => {
  console.log(`Server running on http://${HOST}:${PORT}`);
  
  // Print local IP for easy ESP32 configuration
  const os = require('os');
  const nets = os.networkInterfaces();
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === 'IPv4' && !net.internal) {
        console.log(`[iPARK] Local network URL: ws://${net.address}:${PORT}/ws/iot`);
      }
    }
  }
  
  startStatusSyncJob(io); // Start the brain
});
