// backend/models/ChatMessage.js
// ============================================================
// CHAT MESSAGE MODEL — Stores all support chat messages.
// Messages flow between users and admin/support staff in real-time
// via Socket.IO. Each message belongs to a user's chat room.
// Sessions expire after 1 hour of inactivity or when staff ends them.
// ============================================================
const mongoose = require('mongoose');

const ChatMessageSchema = new mongoose.Schema({
  // The user this conversation belongs to (chat room = userId)
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  // Who actually sent this message (could be user OR admin/support staff)
  senderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  // Display name of the sender (shown in chat bubbles)
  senderName: {
    type: String,
    required: true
  },
  // The actual message text
  message: {
    type: String,
    required: true,
    trim: true
  },
  // true if this message was sent by admin/support staff
  isAdmin: {
    type: Boolean,
    default: false
  },
  // true if this is a system-generated greeting or farewell message
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  // true if this message marks the END of a chat session
  // (sent when staff clicks "End Session")
  isSessionEnd: {
    type: Boolean,
    default: false
  },
  // When this message was sent
  createdAt: {
    type: Date,
    default: Date.now
  },
  // Optional client-side ID to prevent duplicate messages
  clientMsgId: {
    type: String,
    required: false
  }
});

module.exports = mongoose.model('ChatMessage', ChatMessageSchema);
