import 'package:flutter/material.dart';
import 'user_detail_screen.dart';
import 'package:socket_io_client/socket_io_client.dart' as IO;
import '../../services/admin_api_service.dart';
import '../../services/base_api_service.dart';
import '../../theme/app_theme.dart';
import 'package:intl/intl.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../widgets/custom_app_bar.dart';

class AdminChatScreen extends StatefulWidget {
  final String userId;
  final String userName;
  final Map<String, dynamic> user;

  const AdminChatScreen({
    super.key, 
    required this.userId, 
    required this.userName,
    required this.user,
  });

  @override
  State<AdminChatScreen> createState() => _AdminChatScreenState();
}

class _AdminChatScreenState extends State<AdminChatScreen> {
  final AdminApiService _apiService = AdminApiService();
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  late IO.Socket socket;
  List<Map<String, dynamic>> _messages = [];
  bool _isLoading = true;
  String? _adminId;
  String? _adminName;
  bool _isEnding = false;

  @override
  void initState() {
    super.initState();
    _loadAdminData();
    _fetchHistory();
    _initSocket();
  }

  Future<void> _loadAdminData() async {
    final prefs = await SharedPreferences.getInstance();
    setState(() {
      _adminId = prefs.getString('userId');
      _adminName = prefs.getString('userName') ?? "Admin Support";
    });
  }

  void _initSocket() {
    socket = IO.io(BaseApiService.baseUrl.replaceFirst('/api', ''), <String, dynamic>{
      'transports': ['websocket'],
      'autoConnect': false,
    });

    socket.connect();

    socket.onConnect((_) {
      print('Admin connected to socket');
      socket.emit('join_chat', {
        'userId': widget.userId,
        'userName': 'Admin ($_adminName)',
      });
    });

    socket.on('receive_chat_message', (data) {
      if (mounted) {
        final incoming = Map<String, dynamic>.from(data);
        
        // Keep automated messages so admin knows what the user sees
        // if (incoming['isAutoGenerated'] == true) return;

        // Deduplication: Check if this already exists (echoed back by socket)
        bool alreadyExists = _messages.any((m) => 
          m['_id'] == incoming['_id'] || 
          (incoming['clientMsgId'] != null && m['clientMsgId'] == incoming['clientMsgId']) ||
          (m['senderId'].toString() == incoming['senderId'].toString() &&
           m['message'] == incoming['message'] &&
           m['_id'] == null) // identifies our own optimistic message
        );

        if (!alreadyExists) {
          setState(() {
            _messages.add(incoming);
          });
          _scrollToBottom();
        } else {
          // Update the locally-sent optimistic message with final DB data (like _id)
          setState(() {
            final index = _messages.indexWhere((m) => 
              (incoming['clientMsgId'] != null && m['clientMsgId'] == incoming['clientMsgId']) ||
              (m['senderId'].toString() == incoming['senderId'].toString() &&
               m['message'] == incoming['message'] &&
               m['_id'] == null)
            );
            if (index != -1) {
              _messages[index] = incoming;
            }
          });
        }
      }
    });

    socket.onDisconnect((_) => print('Admin disconnected from socket'));
  }

  Future<void> _fetchHistory() async {
    final history = await _apiService.getAdminChatHistory(widget.userId);
    if (mounted) {
      setState(() {
        _messages = history;
        _isLoading = false;
      });
      _scrollToBottom();
    }
  }

  void _sendMessage() {
    if (_messageController.text.trim().isEmpty) return;
    if (_adminId == null) return;
    
    if (!socket.connected) {
       socket.connect();
       return;
    }

    final clientMsgId = "c_${DateTime.now().millisecondsSinceEpoch}_$_adminId";

    final messageData = {
      'userId': widget.userId,
      'senderId': _adminId,
      'senderName': _adminName,
      'message': _messageController.text.trim(),
      'isAdmin': true,
      'createdAt': DateTime.now().toIso8601String(),
      'clientMsgId': clientMsgId,
    };

    setState(() {
      _messages.add(messageData);
    });
    _scrollToBottom();

    socket.emit('send_chat_message', messageData);
    _messageController.clear();
  }

  void _scrollToBottom() {
    Future.delayed(const Duration(milliseconds: 300), () {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  @override
  void dispose() {
    socket.disconnect();
    socket.dispose();
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: CustomAppBar(
        title: widget.userName,
        showBackButton: true,
        showLogo: false,
        showProfile: false,
        leadingPhoto: GestureDetector(
          onTap: () {
             Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => UserDetailScreen(user: widget.user),
              ),
            );
          },
          child: CircleAvatar(
            radius: 16,
            backgroundColor: AppTheme.primaryLight.withOpacity(0.1),
            backgroundImage: widget.user['photoUrl'] != null && widget.user['photoUrl'].toString().isNotEmpty
                ? NetworkImage("${BaseApiService.baseUrl.replaceFirst('/api', '')}/${widget.user['photoUrl']}")
                : null,
            child: widget.user['photoUrl'] == null || widget.user['photoUrl'].toString().isEmpty
                ? Text(
                    (widget.userName.isNotEmpty ? widget.userName[0] : "U").toUpperCase(),
                    style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: AppTheme.primaryLight),
                  )
                : null,
          ),
        ),
        onProfileTap: () => Navigator.pushNamed(context, '/profile'),
        actions: [
          if (!_isEnding)
            IconButton(
              icon: const Icon(Icons.close_rounded, color: Colors.redAccent),
              onPressed: () async {
                final confirm = await showDialog<bool>(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: const Text("End Session?"),
                    content: const Text("This will send a formal goodbye and close the chat for the user in 5 minutes."),
                    actions: [
                      TextButton(onPressed: () => Navigator.pop(context, false), child: const Text("Cancel")),
                      TextButton(
                        onPressed: () => Navigator.pop(context, true), 
                        child: const Text("End Session", style: TextStyle(color: Colors.red))
                      ),
                    ],
                  ),
                );

                if (confirm == true) {
                  setState(() => _isEnding = true);
                  final res = await _apiService.endChatSession(widget.userId);
                  if (res['success'] == true) {
                    if (mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text("Session ended successfully. Bye!"))
                      );
                      Navigator.pop(context);
                    }
                  } else {
                    if (mounted) {
                      setState(() => _isEnding = false);
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(content: Text("Error: ${res['message']}"))
                      );
                    }
                  }
                }
              },
              tooltip: "End Session",
            )
          else
            const Center(
              child: Padding(
                padding: EdgeInsets.only(right: 16),
                child: SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.redAccent)),
              ),
            ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: _isLoading
                ? const Center(child: CircularProgressIndicator(color: AppTheme.primaryLight))
                : ListView.builder(
                    controller: _scrollController,
                    padding: const EdgeInsets.all(16),
                    itemCount: _messages.length,
                    itemBuilder: (context, index) {
                      final msg = _messages[index];
                      final bool isSupport = msg['isAdmin'] == true;
                      final alignment = isSupport ? Alignment.centerRight : Alignment.centerLeft;
                      final time = DateTime.tryParse(msg['createdAt'] ?? '')?.toLocal();

                      final bubbleColor = isSupport ? AppTheme.primaryLight : Colors.blueGrey[700];

                      return Align(
                        alignment: alignment,
                        child: Container(
                          margin: const EdgeInsets.only(bottom: 12),
                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                          constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
                          decoration: BoxDecoration(
                            color: bubbleColor,
                            borderRadius: BorderRadius.only(
                              topLeft: const Radius.circular(15),
                              topRight: const Radius.circular(15),
                              bottomLeft: Radius.circular(isSupport ? 15 : 0),
                              bottomRight: Radius.circular(isSupport ? 0 : 15),
                            ),
                            boxShadow: [
                              BoxShadow(
                                color: Colors.black.withOpacity(0.05),
                                blurRadius: 5,
                                offset: const Offset(0, 2),
                              ),
                            ],
                          ),
                          child: Column(
                            crossAxisAlignment: isSupport ? CrossAxisAlignment.end : CrossAxisAlignment.start,
                            children: [
                              Padding(
                                padding: const EdgeInsets.only(bottom: 4),
                                child: Text(
                                  isSupport 
                                    ? (msg['isAutoGenerated'] == true ? "(Automated)" : (msg['senderName'] ?? "Admin Support"))
                                    : widget.userName,
                                  style: const TextStyle(
                                    fontSize: 10,
                                    fontWeight: FontWeight.bold,
                                    color: Colors.white70,
                                  ),
                                ),
                              ),
                              Text(
                                msg['message'] ?? "",
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 14,
                                ),
                              ),
                              const SizedBox(height: 4),
                              Text(
                                time != null ? DateFormat('HH:mm').format(time) : "",
                                style: const TextStyle(
                                  fontSize: 9,
                                  color: Colors.white70,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ).animate().fadeIn(duration: 300.ms).slideY(begin: 0.1, end: 0);
                    },
                  ),
          ),
          _buildInputArea(),
        ],
      ),
    );
  }

  Widget _buildInputArea() {
    return Container(
      margin: const EdgeInsets.fromLTRB(16, 8, 16, 30),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
      decoration: BoxDecoration(
        color: Theme.of(context).cardColor,
        borderRadius: BorderRadius.circular(25),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.12),
            blurRadius: 15,
            offset: const Offset(0, 8),
          ),
        ],
        border: Border.all(color: AppTheme.primaryLight.withOpacity(0.2)),
      ),
      child: Row(
        children: [
          Expanded(
            child: TextField(
              controller: _messageController,
              decoration: const InputDecoration(
                hintText: "Reply to user...",
                border: InputBorder.none,
                contentPadding: EdgeInsets.symmetric(horizontal: 5, vertical: 12),
              ),
              onSubmitted: (_) => _sendMessage(),
            ),
          ),
          const SizedBox(width: 8),
          IconButton(
            onPressed: _sendMessage,
            icon: const Icon(Icons.send, color: AppTheme.primaryLight, size: 24),
          ),
        ],
      ),
    );
  }
}
